src/Chirp.Web/Pages/AboutMe.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace Chirp.Web.Pages;
[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]

public class AboutMeModel : PageModel
{
    public string? Email { get; private set; }
    public string? DisplayName { get; private set; }
    public string? ProfilePictureUrl { get; private set; }

    // for individual user/"Author" preferences:
    public bool IsDarkMode { get; private set; }
    public float FontSizeScale { get; private set; }
    private readonly IAuthorRepository _authorRepository;

    public AboutMeModel(IAuthorRepository authorRepository)
    {
        _authorRepository = authorRepository;
    }

    /// <summary>
    /// Gets the cheeps from the author with the given currentUserName.
    /// </summary>
    /// <param name="page"></param>
    /// <returns></returns>
    public async Task<ActionResult> OnGet()
    {
        var authors = await _authorRepository.GetAuthorByName(User.Identity?.Name!);
        var author = authors.FirstOrDefault();
        if (author == null || User.Identity == null || !User.Identity.IsAuthenticated)
        {
            return RedirectToPage("public");
        }

        DisplayName = author.DisplayName;
        Email = author.Email != author.Name ? author.Email : "Email...";

        ProfilePictureUrl = await _authorRepository.GetProfilePicture(author.Name);
        IsDarkMode = await _authorRepository.IsDarkMode(User.Identity?.Name!);

        FontSizeScale = await _authorRepository.GetFontSizeScale(User.Identity?.Name!);

        return Page();
    }

    /// <summary>
    /// Changes the email of the author with the given currentUserName to the given newEmail.
    /// </summary>
    /// <param name="newEmail"></param>
    /// <returns></returns>
    public async Task<ActionResult> OnPostChangeEmail(string newEmail)
    {
        try
        {
            await _authorRepository.ChangeEmail(User.Identity?.Name!, newEmail);
            return RedirectToPage();
        }
        catch (ArgumentException e)
        {
            return RedirectToPage("aboutme", new { error = e.Message ?? "Email Already in use." });
        }
        catch
        {
            return RedirectToPage("aboutme", new { error = "Error Chaning Email" });
        }
    }

    public async Task<IActionResult> OnPostChangeName(string newName)
    {
        try
        {
            await _authorRepository.ChangeName(User.Identity?.Name!, newName);
            return RedirectToPage();
        }
        catch (ArgumentException e)
        {
            return RedirectToPage("aboutme", new { error = e.Message ?? "Username Already in use." });
        }
        catch
        {
            return RedirectToPage("aboutme", new { error = "Error Chaning Username" });
        }
    }

    /// <summary>
    /// Follows the author with the given followName from the author with the given currentUserName.
    /// </summary>
    /// <param name="authorName"></param>
    /// <returns></returns>
    public async Task<ActionResult> OnPostDeleteAccount(string authorName)
    {
        try
        {
            await _authorRepository.DeleteAuthor(authorName);

            // Need to signout the user
            return Redirect("MicrosoftIdentity/Account/SignOut");
        }
        catch
        {
            return RedirectToPage("aboutme", new { error = "Could not delete user. Author " + authorName + " does not exist" });
        }
    }

    public async Task<IActionResult> OnPostSetDarkMode()
    {
        var isDarkMode = !await _authorRepository.IsDarkMode(User.Identity?.Name!);

        await _authorRepository.SetDarkMode(User.Identity?.Name!, isDarkMode);
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostSetFontSizeScale(float scale)
    {
        if (scale == 15)
        {
            scale = 1.5F;
        }

        if (scale < 1 || scale > 2)
        {
            return RedirectToPage();
        }

        await _authorRepository.SetFontSizeScale(User.Identity?.Name!, scale);
        return RedirectToPage();
    }
}

src/Chirp.Web/Pages/FollowView.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages;
[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]
public class FollowViewModel : PageModel
{
    private readonly IAuthorRepository _authorRepository;

    public List<AuthorDTO> FollowersList { get; set; }
    public List<AuthorDTO> FollowingList { get; set; }
    public PaginationModel? Pagination { get; private set; }
    public string? ProfilePictureUrl { get; private set; }
    public bool IsDarkMode { get; private set; }
    public float FontSizeScale { get; private set; }

    public FollowViewModel(ICheepRepository repository, IAuthorRepository authorRepository)
    {
        FollowersList = new List<AuthorDTO>();
        FollowingList = new List<AuthorDTO>();
        _authorRepository = authorRepository;
        IsDarkMode = false;
    }

    public async Task<ActionResult> OnGet([FromQuery] int page, string author, string followType)
    {
        if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            ProfilePictureUrl = await _authorRepository.GetProfilePicture(User.Identity.Name!);
            IsDarkMode = await _authorRepository.IsDarkMode(User.Identity.Name!);
            FontSizeScale = await _authorRepository.GetFontSizeScale(User.Identity.Name!);
        }

        // If a page query is not given in the url set the page=1
        page = page <= 1 ? 1 : page;

        var myFollowing = await _authorRepository.GetFollowing(author);
        var followingDtos = myFollowing.ToList();
        FollowingList = followingDtos;

        if (followType == "following")
        {
            var nFollowing = followingDtos.Count;
            Pagination = new PaginationModel(nFollowing, page);
            return Page();
        }

        var myFollowers = await _authorRepository.GetFollowers(author);
        var followersDtos = myFollowers.ToList();
        FollowersList = followersDtos;

        var nAuthors = followersDtos.Count;
        Pagination = new PaginationModel(nAuthors, page);

        return Page();
    }
}

src/Chirp.Web/Pages/FollowingView.cshtml.cs
using Chirp.core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Chirp.core.DTOs;
using Chirp.Web.Pages.Shared;

namespace Chirp.Web.Pages;

public class FollowingModel : PageModel
{
    private readonly ICheepRepository _repository;
    private readonly IAuthorRepository _authorRepository;
    public List<CheepDTO> Cheeps { get; private set; }
    public PaginationModel? Pagination { get; private set; }
    
    public FollowingModel(ICheepRepository repository, IAuthorRepository authorRepository)
    {
        Cheeps = new List<CheepDTO>();
        _repository = repository;
        _authorRepository = authorRepository;
    }

    public async Task<ActionResult> OnGet([FromQuery] int page)
    {
        //If a page query is not given in the url set the page=1
        page = page <= 1 ? 1 : page;
        
        var myFollowing = await _authorRepository.GetFollowing(User.Identity?.Name!);
        foreach (var author in myFollowing)
        {
            var cheeps = _repository.GetCheepFromAuthor(author.Name, page).Result.ToList();
            Cheeps.AddRange(cheeps);
        }
        
        var nCheeps = Cheeps.Count;
        Pagination = new PaginationModel(nCheeps, page);
        
        return Page();
    }
}

src/Chirp.Web/Pages/Public.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;

namespace Chirp.Web.Pages;
[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]
public class PublicModel : PageModel
{
    public static PaginationModel Pagination { get; private set; } = new(1, 1);
    public string? ProfilePictureUrl { get; private set; }
    public string? DisplayName { get; private set; }
    public bool IsDarkMode { get; private set; }
    public float FontSizeScale { get; private set; }
    private readonly ICheepRepository _cheepRepository;
    private readonly IAuthorRepository _authorRepository;
    private readonly IReactionRepository _reactionRepository;
    private static List<CheepDTO> Cheeps { get; set; } = new();

    public PublicModel(ICheepRepository cheepRepository, IAuthorRepository authorRepository, IReactionRepository reactionRepository)
    {
        IsDarkMode = false;
        _cheepRepository = cheepRepository;
        _authorRepository = authorRepository;
        _reactionRepository = reactionRepository;
    }

    public async Task<IActionResult> OnGet([FromQuery] int page)
    {
        // If a page query is not given in the url set the page=1
        page = page <= 1 ? 1 : page;

        var nCheeps = _cheepRepository.CountCheeps().Result;
        Pagination = new PaginationModel(nCheeps, page);

        if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            await _authorRepository.EnsureAuthorExists(User.Identity.Name!);
            ProfilePictureUrl = await _authorRepository.GetProfilePicture(User.Identity.Name!);
            IsDarkMode = await _authorRepository.IsDarkMode(User.Identity.Name!);
            FontSizeScale = await _authorRepository.GetFontSizeScale(User.Identity.Name!);
            DisplayName = await _authorRepository.GetDisplayName(User.Identity.Name!);
        }

        Cheeps = _cheepRepository.GetCheep(page).Result.ToList();

        return Page();
    }

    public List<CheepDTO> GetCheeps()
        => Cheeps;

    public PaginationModel GetPagination()
        => Pagination;

    public IActionResult OnPostCheep(string message)
    {
        if (message.IsNullOrEmpty()) return RedirectToPage("Public", new { error = "Cheep must not be empty" });
        try
        {
            _cheepRepository.CreateCheep(message, User.Identity?.Name!);
            return RedirectToPage("Public");
        }
        catch
        {
            return RedirectToPage("Public", new { error = "Error posting cheep" });
        }
    }

    public IActionResult OnPostChangeReaction(string cheepId, string reactionType)
    {
        var author = User.Identity?.Name!;
        if (!(User.Identity?.IsAuthenticated ?? false) || author == "") return RedirectToPage("Public", new { error = "You must be logged in to react" });

        var cheepReactions = Cheeps.First(c => c.CheepId == cheepId).Reactions;
        if (cheepReactions.Any(r => r.Author == author))
        {
            var prevReaction = cheepReactions.First(r => r.Author == author);
            cheepReactions.Remove(prevReaction);
            _reactionRepository.RemoveReaction(cheepId, author);
            if (prevReaction.ReactionType == reactionType) return RedirectToPage("Public");
        }

        cheepReactions.Add(new ReactionDTO(cheepId, author, reactionType));
        _reactionRepository.CreateReaction(cheepId, author, reactionType);
        return RedirectToPage("Public");
    }

    public async Task<string?> GetProfilePicture(string name)
    {
        return await _authorRepository.GetProfilePicture(name);
    }
}

src/Chirp.Web/Pages/UserTimeline.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages;
[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]
public class UserTimelineModel : PageModel
{
    private readonly ICheepRepository _cheepRepository;
    private readonly IAuthorRepository _authorRepository;
    private readonly IReactionRepository _reactionRepository;
    public static List<CheepDTO> Cheeps { get; set; } = new();
    public static PaginationModel Pagination { get; private set; } = new(1, 1);
    public int FollowingCount { get; set; }
    public int FollowersCount { get; set; }
    public bool IsFollowingAuthor { get; set; }
    public string? ProfilePictureUrl { get; private set; }
    public string? AuthorProfilePictureUrl { get; private set; }
    public bool IsDarkMode { get; private set; }
    public float FontSizeScale { get; private set; }

    public UserTimelineModel(ICheepRepository cheepRepository, IAuthorRepository authorRepository, IReactionRepository reactionRepository)
    {
        _cheepRepository = cheepRepository;
        _authorRepository = authorRepository;
        _reactionRepository = reactionRepository;
        FollowingCount = 0;
        IsDarkMode = false;
    }

    public List<CheepDTO> GetCheeps()
        => Cheeps;

    public PaginationModel GetPagination()
        => Pagination;

    public async Task<ActionResult> OnGet(string author, [FromQuery] int page)
    {
        // If a page query is not given in the url set the page=1
        page = page <= 1 ? 1 : page;

        var nCheeps = await _cheepRepository.CountCheepsFromAuthor(author);
        Pagination = new PaginationModel(nCheeps, page);

        Cheeps = _cheepRepository.GetCheepFromAuthor(author, page).Result.ToList();

        var following = await _authorRepository.GetFollowing(author);
        FollowingCount = following.Count();

        var followers = await _authorRepository.GetFollowers(author);
        FollowersCount = followers.Count();
        AuthorProfilePictureUrl = await _authorRepository.GetProfilePicture(author);

        if (User.Identity == null || User.Identity.Name == null)
        {
            return Page();
        }

        var myFollowing = await _authorRepository.GetFollowing(User.Identity!.Name);
        var pageUser = await _authorRepository.GetAuthorByName(author);
        IsFollowingAuthor = myFollowing.Contains(pageUser.FirstOrDefault());

        if (User.Identity.IsAuthenticated)
        {
            ProfilePictureUrl = await _authorRepository.GetProfilePicture(User.Identity.Name!);
            IsDarkMode = await _authorRepository.IsDarkMode(User.Identity.Name!);
            FontSizeScale = await _authorRepository.GetFontSizeScale(User.Identity.Name!);
        }

        return Page();
    }

    /// <summary>
    /// Unfollows the author with the given author name.
    /// </summary>
    /// <param name="author"></param>
    /// <returns></returns>
    public async Task<ActionResult> OnPostUnfollow(string author)
    {
        try
        {
            await _authorRepository.UnfollowAuthor(author, User.Identity?.Name!);
            return RedirectToPage();
        }
        catch
        {
            return RedirectToPage();
        }
    }

    /// <summary>
    /// Follows the author with the given author name.
    /// </summary>
    /// <param name="author"></param>
    /// <returns></returns>
    public async Task<ActionResult> OnPostFollow(string author)
    {
        try
        {
            await _authorRepository.FollowAuthor(author, User.Identity?.Name!);
            return RedirectToPage();
        }
        catch
        {
            return RedirectToPage();
        }
    }

    public async Task<IActionResult> OnPostUploadProfilePicture(IFormFile profilePicture)
    {
        try
        {
            await _authorRepository.UploadProfilePicture(User.Identity?.Name!, profilePicture);
            return RedirectToPage();
        }
        catch (ArgumentException e)
        {
            return RedirectToPage("usertimeline", new { error = e.Message ?? "Invalid File" });
        }
        catch
        {
            return RedirectToPage("usertimeline", new { error = "Error Uploading Profile Picture" });
        }
    }

    public void OnPostChangeReaction(string cheepId, string reactionType)
    {
        var author = User.Identity?.Name!;
        if (!(User.Identity?.IsAuthenticated ?? false) || author == "") return;

        var cheepReactions = Cheeps.First(c => c.CheepId == cheepId).Reactions;
        if (cheepReactions.Any(r => r.Author == author))
        {
            var prevReaction = cheepReactions.First(r => r.Author == author);
            cheepReactions.Remove(prevReaction);
            _reactionRepository.RemoveReaction(cheepId, author);
            if (prevReaction.ReactionType == reactionType) return;
        }

        cheepReactions.Add(new ReactionDTO(cheepId, author, reactionType));
        _reactionRepository.CreateReaction(cheepId, author, reactionType);
    }
}

src/Chirp.Web/Pages/AboutMe.cshtml
@page "/AboutMe"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model AboutMeModel
@{
    ViewData["Title"] = "Chirp! - About Me";
    Layout = "Shared/_StandardLayout";
}

@if (User.Identity?.IsAuthenticated ?? false)
{
    <div onclick=toggleName()>
        <div onclick=toggleEmail()>
            <div class="aboutme_lined_header">
                <span class="aboutme_header_txt">
                    About Me
                </span>
            </div>
            <br><br>
            <div style="margin-left: 1.5rem">
                <h5>Username:</h5>
                <form method="post">
                    <textarea onfocus=show('username') class="aboutme" id="username" rows="1" maxlength="20" name="newName" placeholder="@Model.DisplayName"></textarea>
                    <button id="changeusername" hidden class="changer" asp-page-handler="ChangeName">Change</button>
                </form>
                <br/>
                <h5>Email:</h5>
                <form method="post">
                    <textarea onfocus=show('email') class="aboutme" id="email" rows="1" maxlength="20" name="newEmail" placeholder="@Model.Email"></textarea>
                    <button id="changeemail" hidden class="changer" asp-page-handler="changeemail">Change</button>
                </form>
                <br/>
            </div>
        </div>
    </div>    
            
    <br/>
    <div class="aboutme_lined_header">
        <span class="aboutme_header_txt">
            Appearance
        </span>
    </div>
    <br><br>
    <ul class="settings_ul">
        <li class="settings_li">
            <h5>Dark mode</h5>
            @if (Model.IsDarkMode)
            {
                <i>Disable dark mode</i>
            }
            else
            {
                <i>Enable dark mode</i>
            }
        </li>
        
        <li class="settings_li">
            <label class="switch">
                <form method="post">
                    @if(Model.IsDarkMode)
                    {
                        <input type="checkbox" name="darkmode" checked onclick="clickDarkMode()">
                    }else
                    {
                        <input type="checkbox" name="darkmode" onclick="clickDarkMode()">
                    }
                    <span class="slider round"></span>
                    <button id="darkmode_btn" style="display: none" asp-page-handler="SetDarkMode"></button>
                </form>
            </label>
        </li>
    </ul>
    <br/>
    <ul class="settings_ul">
        <li class="settings_li">
            <h5>Font size</h5>
            <i>Scale font size</i>
        </li>
        
        <li class="settings_li">
            <form method="post" asp-page-handler="SetFontSizeScale" class="SetFontSizeScale">
                <select id="scale" name="scale" onchange="clickFontSize()">
                    @if (Model.FontSizeScale == 1)
                    {
                        <option value="1" selected>1x</option>
                    }
                    else
                    {
                        <option value="1">1x</option>
                    }
                    @if(Model.FontSizeScale == 1.5)
                    {
                        <option value="1.5" selected>1.5x</option>
                    }
                    else
                    {
                        <option value="1.5">1.5x</option>
                    }
                    @if(Model.FontSizeScale == 2)
                    {
                        <option value="2" selected>2x</option>
                    }
                    else
                    {
                        <option value="2">2x</option>
                    }
                </select>
                <input id="submit_btn" type="submit" style="display: none"/>
            </form>
        </li>
    </ul>
    
    <br>
    <div class="aboutme_lined_header">
        <span class="aboutme_header_txt" style="color: red">
            Danger Zone
        </span>
    </div>
    <br><br>
        <ul class="settings_ul">
            <li class="settings_li">
                <h5>Delete your account</h5>
                <i>Warning: This action is irreversible!</i>
            </li>
            <li>
                <form method="post">
                    <button asp-page-handler="DeleteAccount" name=authorName value="@User.Identity.Name" class="delete">Delete your account</button>
                </form>
            </li>
        </ul>
}

<script>
    function clickDarkMode() {
        document.getElementById("darkmode_btn").click();
    }
    
    function clickFontSize() {
        document.getElementById("submit_btn").click();
    }
    let show = (objectID) => {
        let buttonid = "change" + objectID
        document.getElementById(buttonid).removeAttribute("hidden");
        const eventHandler = (e) => hideOnClickOutside(e, buttonid, eventHandler, objectID)
        document.addEventListener("click", eventHandler)
    };

    let hideOnClickOutside = (event, elementToHide, eventHandler, ...exceptIDs) => {
        let exceptObjects = exceptIDs.map((id) => document.getElementById(id))
        if (!exceptObjects.includes(event.target)) {
            document.getElementById(elementToHide).setAttribute("hidden", "hidden")
            document.removeEventListener('click', eventHandler);
        };
    }
</script>


src/Chirp.Web/Pages/FollowView.cshtml
@page "/FollowView/{author}/{followType}"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model FollowViewModel

@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_StandardLayout";
    var author = HttpContext.GetRouteValue("author")!.ToString();
    var followType = HttpContext.GetRouteValue("followType")!.ToString();
}

<div>
    @{
        if (followType == "following")
        {
            if (Model.FollowingList.Any())
            {
                <ul id="messagelist" class="cheeps">
                    @foreach (var user in Model.FollowingList)
                    {
                        <li>
                            <p>
                                 @if (!string.IsNullOrEmpty(user.ProfilePictureUrl)){
                                     <img src="@user.ProfilePictureUrl" width="30" alt="Avatar" class="avatar"  onerror="this.src='/images/default_user_pic.png';">
                                 }
                                 else
                                 {
                                     <img src="~/images/default_user_pic.png" width="30" alt="Avatar" class="avatar">
                                     
                                 }
                                <strong>
                                    @if (string.IsNullOrEmpty(user.DisplayName))
                                    {
                                        <a href="/@user.Name">@user.Name</a>
                                    }
                                    else
                                    {
                                        <a href="/@user.Name">@user.DisplayName</a>
                                    }
                                </strong>
                            </p>
                        </li>
                    }
                </ul>
            }
            else
            {
                <em>You are not following anybody!</em>
            }
        }
        else
        {
            if (Model.FollowersList.Any())
            {
                <ul id="messagelist" class="cheeps">
                    @foreach (var user in Model.FollowersList)
                    {
                        <li>
                            <p>
                                @if (!string.IsNullOrEmpty(user.ProfilePictureUrl)){
                                    <img src="@user.ProfilePictureUrl" width="30" alt="Avatar" class="avatar"  onerror="this.src='/images/default_user_pic.png';">
                                }
                                else
                                {
                                    <img src="~/images/default_user_pic.png" width="30" alt="Avatar" class="avatar">

                                }
                                <strong>
                                    @if (string.IsNullOrEmpty(user.DisplayName))
                                    {
                                        <a href="/@user.Name">@user.Name</a>

                                    }
                                    else
                                    {
                                        <a href="/@user.Name">@user.DisplayName</a>

                                    }
                                </strong>
                            </p>
                        </li>
                    }
                </ul>
            }
            else
            {
                <em>No followers here :(</em>
            }
        }
        <br/>
        {
        await Html.RenderPartialAsync("Shared/Pagination", Model.Pagination);
        }
    }
</div>

src/Chirp.Web/Pages/Public.cshtml
@page "/"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PublicModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_StandardLayout";
}

    @if (User.Identity?.IsAuthenticated ?? false)
    {
        <h2> Write a cheep! </h2>
        <form method="post" asp-page-handler="cheep" class="cheep" style="">
            <textarea id="cheepbox" class="cheepbox" rows="4" maxlength="160" name="message" oninput="countChars()"  placeholder= "What's on your heart, @Model.DisplayName"></textarea>
            <div class="char-count" id="charCount"><p>0/160 characters<p></div>
            <button class="share"><i class="fa fa-send"></i> Cheep!</button>
        </form>

        <script>
            function countChars() {
                var textEntered = document.getElementById('cheepbox').value;
                var textLength = textEntered.length;

                if (textLength <= 160) {
                    document.getElementById('charCount').innerHTML = textLength + '/160 characters';
                } else {

                    document.getElementById('cheepbox').value = textEntered.substring(0, 160);
                    document.getElementById('charCount').innerHTML = '160/160 characters';
                }
            }
        </script>

        <!-- Line breaks -->
        <br />
        <br />
    }

    <h2> Public Timeline </h2>

    @if (Model.GetCheeps().Any())
    {
        <ul id="messagelist" class="cheeps">
            @foreach (var cheep in Model.GetCheeps())
            {
                <li>
                    @{
                        ViewData["Cheep"] = cheep;
                    }
                    <partial name="CheepBox" view-data="ViewData"/>
                </li>
            }
        </ul>
    }
    else
    {
        <em>There are no cheeps so far.</em>
    }

    <br/>
    
    <partial name="Pagination" model="@Model.GetPagination()"/>

src/Chirp.Web/Pages/UserTimeline.cshtml
@page "/{author}"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model UserTimelineModel

@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_StandardLayout";
    var user = HttpContext.GetRouteValue("author")!.ToString();
}

<div>
    <ul class="img_follow_ul">
        <li>
            @if (user == User.Identity!.Name)
            {
                <div class="profilePicture-container">
                    <form method="post" asp-page-handler="UploadProfilePicture" class="UploadProfilePicture"
                        enctype="multipart/form-data">
                        <input type="file" id="fileInput" style="display:none" name="profilePicture" />
                        <label for="fileInput">
                            <img alt="profilePicture" class="profilePicture_img" src="@Model.ProfilePictureUrl"  onerror="this.src='/images/default_user_pic.png';">
                            <div class="change-text">Change</div>
                            <button id="ChangeProfilePicture_btn" style="display: none"></button>
                        </label>
                    </form>
                </div>
            }
            else
            {
                <div class="profilePicture-container-others">
                    <img style="cursor: default" class="profilePicture_img" src="@Model.AuthorProfilePictureUrl"
                        alt="profile picture"  onerror="this.src='/images/default_user_pic.png';">
                </div>
            }
        </li>
        <li>
            <a href="/FollowView/@user/following">@($"Following: {Model.FollowingCount}")</a>
        </li>
        <li>
            <a href="/FollowView/@user/follower">@($"Followers: {Model.FollowersCount}")</a>
        </li>
    </ul>
    <h5> @user's Timeline </h5>

    @if (User.Identity!.IsAuthenticated)
    {
        @if (user != User.Identity!.Name!)
        {
            if (Model.IsFollowingAuthor)
            {
                <form form asp-page-handler="Unfollow" method="post">
                    <button class="share" type="submit"><i class="fa fa-send"></i> Unfollow</button>
                </form>
            }
            else
            {
                <form form asp-page-handler="Follow" method="post">
                    <button class="share" type="submit"><i class="fa fa-send"></i> Follow</button>
                </form>
            }
        }
    }
    @if (Model.GetCheeps().Any())
    {
        <ul id="messagelist" class="cheeps">
            @foreach (var cheep in Model.GetCheeps())
            {
                <li>
                    @{
                        ViewData["Cheep"] = cheep;
                    }
                    <partial name="CheepBox" view-data="ViewData"/>
                </li>
            }
        </ul>
    }
    else
    {
        <em>There are no cheeps so far.</em>
    }
    <br/>
    
    <partial name="Pagination" model="@Model.GetPagination()"/>
</div>

@if (user == User.Identity.Name)
{
    <script>
    document.getElementById("fileInput").addEventListener("change", function () {
        document.getElementById("ChangeProfilePicture_btn").click();
    });

</script>
}