src/Chirp.Web/Pages/Public.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;

namespace Chirp.Web.Pages;
[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]
public class PublicModel : PageModel
{
    public static PaginationModel Pagination { get; private set; } = new(1, 1);
    public string? ProfilePictureUrl { get; private set; }
    public string? DisplayName { get; private set; }
    public bool IsDarkMode { get; private set; }
    public float FontSizeScale { get; private set; }
    private readonly ICheepRepository _cheepRepository;
    private readonly IAuthorRepository _authorRepository;
    private readonly IReactionRepository _reactionRepository;
    private static List<CheepDTO> Cheeps { get; set; } = new();

    public PublicModel(ICheepRepository cheepRepository, IAuthorRepository authorRepository, IReactionRepository reactionRepository)
    {
        IsDarkMode = false;
        _cheepRepository = cheepRepository;
        _authorRepository = authorRepository;
        _reactionRepository = reactionRepository;
    }

    public async Task<IActionResult> OnGet([FromQuery] int page)
    {
        // If a page query is not given in the url set the page=1
        page = page <= 1 ? 1 : page;

        var nCheeps = _cheepRepository.CountCheeps().Result;
        Pagination = new PaginationModel(nCheeps, page);

        if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            await _authorRepository.EnsureAuthorExists(User.Identity.Name!);
            ProfilePictureUrl = await _authorRepository.GetProfilePicture(User.Identity.Name!);
            IsDarkMode = await _authorRepository.IsDarkMode(User.Identity.Name!);
            FontSizeScale = await _authorRepository.GetFontSizeScale(User.Identity.Name!);
            DisplayName = await _authorRepository.GetDisplayName(User.Identity.Name!);
        }

        Cheeps = _cheepRepository.GetCheep(page).Result.ToList();

        return Page();
    }

    public List<CheepDTO> GetCheeps()
        => Cheeps;

    public PaginationModel GetPagination()
        => Pagination;

    public IActionResult OnPostCheep(string message)
    {
        if (message.IsNullOrEmpty()) return RedirectToPage("Public", new { error = "Cheep must not be empty" });
        try
        {
            _cheepRepository.CreateCheep(message, User.Identity?.Name!);
            return RedirectToPage("Public");
        }
        catch
        {
            return RedirectToPage("Public", new { error = "Error posting cheep" });
        }
    }

    public IActionResult OnPostChangeReaction(string cheepId, string reactionType)
    {
        var author = User.Identity?.Name!;
        if (!(User.Identity?.IsAuthenticated ?? false) || author == "") return RedirectToPage("Public", new { error = "You must be logged in to react" });

        var cheepReactions = Cheeps.First(c => c.CheepId == cheepId).Reactions;
        if (cheepReactions.Any(r => r.Author == author))
        {
            var prevReaction = cheepReactions.First(r => r.Author == author);
            cheepReactions.Remove(prevReaction);
            _reactionRepository.RemoveReaction(cheepId, author);
            if (prevReaction.ReactionType == reactionType) return RedirectToPage("Public");
        }

        cheepReactions.Add(new ReactionDTO(cheepId, author, reactionType));
        _reactionRepository.CreateReaction(cheepId, author, reactionType);
        return RedirectToPage("Public");
    }

    public async Task<string?> GetProfilePicture(string name)
    {
        return await _authorRepository.GetProfilePicture(name);
    }
}

src/Chirp.Web/Pages/Shared/CheepBox.cshtml.cs
using System.Diagnostics.CodeAnalysis;

namespace Chirp.Web.Pages.Shared;

[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]
public class CheepBoxModel
{
    public CheepDTO Cheep { get; private set; }

    public CheepBoxModel(CheepDTO cheep)
    {
        Cheep = cheep;
    }
}

src/Chirp.Web/Pages/Shared/PageNumbering.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages.Shared;

public class PaginationModel : PageModel
{
    public readonly int CheepsPerPage = 32;
    public readonly int NPages;
    public readonly int CurrentPage;

    public PaginationModel(int nCheeps, int currentPage)
    {
        CurrentPage = currentPage;
        NPages = nCheeps / CheepsPerPage;
        if (nCheeps % CheepsPerPage > 0) NPages++;
    }
}

src/Chirp.Web/Pages/Shared/Pagination.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages.Shared;
[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileNameMustMatchTypeName", Justification = "Razor Page")]
public class PaginationModel : PageModel
{
    public int CheepsPerPage { get; private set; } = 32;
    public int NPages { get; private set; }
    public int CurrentPage { get; private set; }

    public PaginationModel(int nCheeps, int currentPage)
    {
        CurrentPage = currentPage;
        NPages = nCheeps / CheepsPerPage;
        if (nCheeps % CheepsPerPage > 0) NPages++;
    }
}

src/Chirp.Web/Pages/Shared/CheepBox.cshtml
@{
    CheepDTO cheep;
    if (ViewData["Cheep"] is CheepDTO c) cheep = c;
    else throw new AggregateException("Cheep is not of type CheepDTO");
}

<p>
    @if (!string.IsNullOrEmpty(cheep.ProfilePictureUrl)){
        <img src="@cheep.ProfilePictureUrl" width="30" alt="Avatar" class="avatar" onerror="this.src='/images/default_user_pic.png';">
    }
    else
    {
        <img src="/images/default_user_pic.png" width="30" alt="Avatar" class="avatar">
    }

    <strong>
        @if (cheep.DisplayName != "")
        {
            <a href="/@cheep.Author">@cheep.DisplayName</a>
        }
        else
        {
            <a href="/@cheep.Author">@cheep.Author</a>
        }
        <small>&mdash; @cheep.Timestamp</small>
    </strong>
    <br/>
    @cheep.Message
    <br>

    @{
        ViewData["Cheep"] = cheep;
    }
    <partial name="ReactionBox" view-data="ViewData"/>
</p>

src/Chirp.Web/Pages/Shared/DropDownMenu.cshtml
@using Microsoft.AspNetCore.Authentication.OpenIdConnect
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web

@inject IOptionsMonitor<MicrosoftIdentityOptions> AzureAdb2COptions

@{
    var options = AzureAdb2COptions.Get(OpenIdConnectDefaults.AuthenticationScheme);
}

<ul class="navbar-nav">
    @if (User.Identity!.IsAuthenticated)
    {
        <div class="dropdown">
            <button id="dropbtn" class="dropbtn" onclick="toogleFunction()"></button>
            <label for="dropbtn">
                <img class="profilePicture_img_nav" src="@Model.ProfilePictureUrl" alt="profile picture"  onerror="this.src='/images/default_user_pic.png';">
            </label>
            
            <div id="dropdown" class="dropdown-content">
                <a href="\@User.Identity.Name" class="fa">&#xf15c; My page</a>
                <hr style="margin: 0"/>
                <a class="fa" href="\AboutMe">&#xf013; Settings</a>
                <hr style="margin: 0"/>
                <a asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut" class="fa">&#xf08b; Sign out</a>
            </div>
        </div>
    }
    else
    {
    <a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Sign in</a>
    }
</ul>

<script>
   /* When the user clicks on the button, 
   toggle between hiding and showing the dropdown content */
   function toogleFunction() {
     document.getElementById("dropdown").classList.toggle("show");
   }
   
   // Close the dropdown if the user clicks outside of it
   window.onclick = function(event) {
     if (!event.target.matches('.dropbtn')) {
       const dropdowns = document.getElementsByClassName("dropdown-content");
       let i;
       for (i = 0; i < dropdowns.length; i++) {
         var openDropdown = dropdowns[i];
         if (openDropdown.classList.contains('show')) {
           openDropdown.classList.remove('show');
         }
       }
     }
   }
</script>

src/Chirp.Web/Pages/Shared/PageNumbering.cshtml
@model Chirp.Web.Pages.Shared.PaginationModel
@{
    @if (Model.CurrentPage == 1) {<text>Previous</text>}
    else {<a href="?page=@(Model.CurrentPage - 1)">Previous</a>}
    <text>|</text>
    
    @for (var i = 1; i <= Model.NPages; i++)
    {
        @if (i == Model.CurrentPage) {<text>@i</text>}
        else {<a href="?page=@i">@i</a>}
        <text>|</text>
    }
    
    @if (Model.CurrentPage == Model.NPages) {<text>Next</text>}
    else {<a href="?page=@(Model.CurrentPage+1)">Next</a>}
}

src/Chirp.Web/Pages/Shared/Pagination.cshtml
@model Chirp.Web.Pages.Shared.PaginationModel
@{
    <ul id="pagination_ul">
        @if (Model.CurrentPage == 1)
        {
            <li><p>Previous</p></li>
        }
        else
        {
            <li><a href="?page=@(Model.CurrentPage - 1)">Previous</a></li>
        }
        <li>
            <p>|</p></li>
        @for (var i = 1; i <= Model.NPages; i++)
        {
            @if (i == Model.CurrentPage)
            {
                <li>
                    <p>@i</p></li>
            }
            else
            {
                <li><a href="?page=@i">@i</a></li>
            }
            <li>
                <p>|</p></li>
        }

        @if (Model.CurrentPage == Model.NPages)
        {
            <li>
                <p>Next</p></li>
        }
        else
        {
            <li><a href="?page=@(Model.CurrentPage + 1)">Next</a></li>
        }
    </ul>
}

src/Chirp.Web/Pages/Shared/ReactionBox.cshtml
@using Humanizer
<div style="display: inline-block">

@{
    CheepDTO cheep;
    if (ViewData["Cheep"] is CheepDTO c) cheep = c;
    else throw new AggregateException("Cheep is not of type CheepDTO");
    
    var reactionTypes = Enum.GetValues<ReactionType>().Select(r => (r.ToString(), r.Humanize()));
}

@if (!User.Identity?.IsAuthenticated ?? false)
{
    <text>|</text>
    @foreach (var (reactionType, displayString) in reactionTypes)
    {
        <text>@displayString : </text>
        @cheep.Reactions.Count(r => r.ReactionType == reactionType)
        <text>|</text>
    }
}
else
{
    var author = User.Identity?.Name!;
    var hasReacted = cheep.Reactions.FirstOrDefault(r => r.Author == author)?.ReactionType;

    @foreach (var (reactionType, displayString) in reactionTypes)
    {
        <form method="post" style="display: inline-block">
            <input type="hidden" name="cheepId" value=@cheep.CheepId>
            <input type="hidden" name="reactionType" value=@reactionType>
            <button style="background-color:@(hasReacted == reactionType ? "#cc6e6e" : "")" asp-page-handler="ChangeReaction">
                @displayString :
                @cheep.Reactions.Count(r => r.ReactionType == reactionType)
            </button>
        </form>
    }
}
</div>

src/Chirp.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css"/>    
    <link href="~/css/fontSize1x.css" rel="stylesheet" type="text/css"/>
    <link rel="icon" type="image/png" href="/favicon/favicon.ico">
    <link href="~/lib/font-awesome/font-awesome.min.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class=page>
    <div class="header">
        <h1><img src="/images/icon1.png" alt="Icon1"/>Chirp!</h1>
        <div id="sticky_nav">    
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
                <div class="container">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a style="margin-right: 1rem" asp-area="" asp-page="/Public">Home</a>
                            </li>
                            <li>
                                @if (User.Identity!.IsAuthenticated)
                                {
                                    <a  asp-area="" asp-page="/FollowingTimeline">Following timeline</a>
                                    
                                }
                            </li>
                        </ul>
                        <partial name="DropDownMenu"/>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class=footer>
        Chirp &mdash; An ASP.NET Application by group 18
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

src/Chirp.Web/Pages/Shared/_StandardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @if (Model.IsDarkMode)
    {
        <link href="~/css/darkmode.css" rel="stylesheet" type="text/css"/>
    }
    else
    {
        <link href="~/css/style.css" rel="stylesheet" type="text/css"/>    
    }
    
    @{
        var cssLink = "";
    }
    
    @if (Model.FontSizeScale == 2)
    {
        cssLink = "/css/fontSize2x.css";
    }
    else if (Model.FontSizeScale == 1.5)
    {
        cssLink = "/css/fontSize1_5x.css";
    }
    else
    {
        cssLink = "/css/fontSize1x.css";
    }
    <link href="@cssLink" rel="stylesheet" type="text/css"/>
    <link href="~/lib/font-awesome/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link rel="icon" type="image/png" href="/favicon/favicon.ico">
</head>
<body>
<div class=page>
    <div class="header">
        <h1><img src="/images/icon1.png" alt="Icon1"/>Chirp!</h1>
        <div id="sticky_nav">    
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
                <div class="container">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a style="margin-right: 1rem" asp-area="" asp-page="/Public">Home</a>
                            </li>
                            <li>
                                @if (User.Identity!.IsAuthenticated)
                                {
                                    <a  asp-area="" asp-page="/FollowingTimeline">Following timeline</a>
                                    
                                }
                            </li>
                        </ul>
                        <partial name="DropDownMenu"/>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class=footer>
        Chirp &mdash; An ASP.NET Application by group 18
    </div>
</div>
<div id="error-notification" hidden onclick="hideErrorNotification()">
    <h2>Error:</h2>
    <p id="error-message"></p>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)

<script>
    const hideErrorNotification = () => {document.getElementById('error-notification').hidden = true}
    (() => {
        const errorMsg = new URLSearchParams(window.location.search).get("error")
        const currentUrl = window.location.href;
        const newUrl = currentUrl.replace(/[?&]error=[^&]+/, '');
        window.history.replaceState({}, document.title, newUrl);
        if (errorMsg != null) {
            document.getElementById("error-message").innerHTML = errorMsg;
            document.getElementById("error-notification").hidden = false;
            setTimeout(function () {
                document.getElementById("error-notification").hidden = true;
            }, 5000);
        }
    })();
</script>
</body>
</html>